[package]
name = "snake"
version = "0.1.0"
authors = ["Daniel Gatis <danielgatis@gmail.com>"]
edition = "2018"

[dependencies]
piston = "0.39.0"
piston2d-graphics = "0.28.0"
pistoncore-glutin_window = "0.51.0"
piston2d-opengl_graphics = "0.57.0"
rand = "0.4"

